Human-Readable option
g0hl1n/xprintidle pull request #14
Opened 2023-07-29 03:18 UTC by Schilive

An option to output the idle time in a human-readable format, using the `--human-readable` option — the option `-h` was not used because it would conflict with the help option, according to the manual. Also, I do not know the .1 format, so I changed it in a way that looked right.

The human-readable format prints the time in human time units. Separates the units by comma, uses as many units as necessary and pluralize the nouns. For example, if the idle time were `61926 ms`, the output of `xprintidle --human-readable` would be 

`1 minute, 1 second, 926 milliseconds`.

2023-08-03 07:30 UTC, g0hl1n requested changes
Thanks for the PR, highly appreciated!

Just one request for change: May you please also add a short option (`-H`) for this?

Thanks.

2023-08-03 12:41 UTC, Schilive commented
Thank you for reviewing. I will do that.

2023-08-04 08:30 UTC, g0hl1n requested changes

2023-08-04 08:30 UTC, g0hl1n commented on xprintidle.1
> +.B \-\^\-human-readable
Please also mention the short option in the manpage. Thanks

2023-08-05 01:12 UTC, Schilive commented
I am sorry. The change you requested looked so simple, it went right over my head.

2023-08-07 09:46 UTC, g0hl1n approved these changes

2023-08-07 09:47 UTC, g0hl1n commented
> Added the information to the manual. I am sorry. The change you requested looked so simple, it went right over my head.

Thanks. No problem :wink:

2023-08-07 09:47 UTC, merged